Temporary workaround update value-acessor-base.ts
Temporary workaround update value-acessor-base.ts to fix Ivy compiler problem:

ERROR in node_modules/@nbfontana/ngx-br/src/app/commons/value-acessor-base.d.ts:18:40 - error TS2314: Generic type 'ValueAccessorBase<T>' requires 1 type argument(s).

static ngBaseDef: ɵngcc0.ɵɵBaseDef<ValueAccessorBase>;

Workaround solution: https://github.com/angular/angular/issues/31160#issuecomment-535648669